# This is a basic workflow to help you get started with Actions

name: Bulid technofesta-project on S3
on:
  push:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master  # リポジトリをチェックアウト

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build  # ビルド

      - name: Deploy  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |　#S3のbucket-for-deploying-technofesta-projectバケットにデプロイ
          aws s3 cp --recursive --region ap-northeast-1 build s3://bucket-for-deploying-technofesta-project
